type User {
	id: ID
	name: String
	avatar: String
	email: String
}

type UsersConnection {
	users: [User]
	pageInfo: PageInfo
}

type PageInfo {
	hasPreviousPage: Boolean
	hasNextPage: Boolean
	startCursor: ID
	endCursor: ID
}

type Query {
	usersConnection(first: Int, after: ID): UsersConnection
}
